#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --distribution bookworm \
    --security false \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --architecture amd64 \
    --iso-application "VoidOS" \
    --iso-publisher "VoidOS Project" \
    --iso-volume "VoidOS" \
    --bootappend-live "boot=live components username=void hostname=voidos quiet splash persistence persistence-label=VoidOS.vospd" \
    --debian-installer false \
    --memtest none \
    --win32-loader false \
    --apt-recommends true \
    --apt-source-archives false \
    --firmware-chroot false \
    "${@}"
