#!/bin/sh
set -e

lb config noauto \
    --distribution trixie \
    --mirror-bootstrap "http://deb.debian.org/debian" \
    --mirror-chroot "http://deb.debian.org/debian" \
    --mirror-binary "http://deb.debian.org/debian" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --debian-installer none \
    --firmware-binary true \
    --firmware-chroot true \
    --apt-recommends true \
    --iso-application "VoidOS" \
    --iso-publisher "Allen Lambert Jr (voltaccept.com)" \
    --iso-volume "VOIDOS" \
    --memtest none \
    --win32-loader false \
    "${@}"
